version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    depends_on:
      - mysql
  client_web:
    build:
      context: client/web
      args:
        NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./client/web:/web
      - ./client/web/package.json:/web/package.json
      - ./client/web/yarn.lock:/web/yarn.lock
      - ./tools/yarn.js:/web/yarn.js
    env_file:
      - ./envs/share.env
      - ./envs/web.env
  server_graph:
    build:
      context: server/graph
      args:
        NODE_ENV: development
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./server/graph:/graph
      - ./server/graph/package.json:/graph/package.json
      - ./server/graph/yarn.lock:/graph/yarn.lock
      - ./tools/yarn.js:/graph/yarn.js
    env_file:
      - ./envs/share.env
      - ./envs/graph.env
volumes:
  mysql:
  yarn: