version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    image: prismagraphql/prisma:1.8
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    depends_on:
      - mysql
  client_web:
    build:
      context: client/web
      args:
        - NODE_ENV
    ports:
      - 3000:3000
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./client/web:/web
      - ./client/web/package.json:/web/package.json
      - ./client/web/yarn.lock:/web/yarn.lock
      - ./tools/yarn.js:/web/yarn.js
    env_file:
      - ./envs/share.env
      - ./envs/web.env
  client_app:
    build:
      context: client/app
      args:
        - NODE_ENV
        - EXPO_USERNAME
        - EXPO_PASSWORD
    ports:
      - 19000:19000
      - 19001:19001
      - 8081:8081
      - "0.0.0.0:4040:4040"
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./client/app:/app
      - ./client/app/package.json:/app/package.json
      - ./client/app/package-lock.json:/app/package-lock.json
      - ./tools/npm.js:/app/npm.js
    env_file:
      - ./envs/share.env
      - ./envs/app.env
  server_graph:
    build:
      context: server/graph
      args:
        - NODE_ENV
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./server/graph:/graph
      - ./server/graph/package.json:/graph/package.json
      - ./server/graph/yarn.lock:/graph/yarn.lock
      - ./tools/yarn.js:/graph/yarn.js
    env_file:
      - ./envs/share.env
      - ./envs/graph.env
  server_api:
    build:
      context: server/api
      args:
        - NODE_ENV
    ports:
      - 4002:4002
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./server/api:/api
      - ./server/api/package.json:/api/package.json
      - ./server/api/yarn.lock:/api/yarn.lock
      - ./tools/yarn.js:/api/yarn.js
    env_file:
      - ./envs/share.env
      - ./envs/api.env
volumes:
  mysql:
  yarn: